[package]
name = "restaurant-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1" , features = ["full"]}
warp = "0.3.7"
rusqlite = "0.32.1"
serde = { version = "1" , features = ["derive"]}
serde_json = "1"